// <auto-generated />
using System;
using Gymora.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymora.Database.Migrations
{
    [DbContext(typeof(GymoraDbContext))]
    [Migration("20260211140918_ChangeFieldMovementPlan")]
    partial class ChangeFieldMovementPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gymora.Database.Entities.CoachModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgramComplete")
                        .HasColumnType("int");

                    b.Property<int>("ProgramImperfect")
                        .HasColumnType("int");

                    b.Property<int>("ProgramRequested")
                        .HasColumnType("int");

                    b.Property<int>("ProgramSet")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Gymora.Database.Entities.MovementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateCoachId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreateCoachId");

                    b.ToTable("MovementModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanDetailModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateCoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Files")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Weight")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("PlanModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanMovementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlanDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PlanDetailId");

                    b.ToTable("PlanMovementModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("QuestionId");

                    b.ToTable("PlanQuestionModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gymora.Database.Entities.Utility.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CreateCoachId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MovementModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateCoachId");

                    b.HasIndex("MovementModelId");

                    b.ToTable("QuestionModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.Utility.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrackingCode")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("Gymora.Database.Entities.VerifyCodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("VerifyCodes");
                });

            modelBuilder.Entity("Gymora.Database.Entities.VideoMovementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateCoachId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateCoachId");

                    b.HasIndex("MovementId");

                    b.ToTable("VideoMovementModels");
                });

            modelBuilder.Entity("Gymora.Database.Entities.CoachModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.UserModel", "User")
                        .WithOne("Coach")
                        .HasForeignKey("Gymora.Database.Entities.CoachModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymora.Database.Entities.MovementModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.CoachModel", "Coach")
                        .WithMany()
                        .HasForeignKey("CreateCoachId");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanDetailModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.PlanModel", "Plan")
                        .WithMany("PlanDetails")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanModel", b =>
                {
                    b.OwnsOne("Gymora.Database.Entities.Utility.BitOperation<Gymora.Database.Entities.WeakMuscle, short>", "WeakMuscle", b1 =>
                        {
                            b1.Property<int>("PlanModelId")
                                .HasColumnType("int");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint");

                            b1.HasKey("PlanModelId");

                            b1.ToTable("PlanModels");

                            b1.WithOwner()
                                .HasForeignKey("PlanModelId");
                        });

                    b.Navigation("WeakMuscle");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanMovementModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.MovementModel", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymora.Database.Entities.PlanMovementModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Gymora.Database.Entities.PlanDetailModel", "PlanDetail")
                        .WithMany("PlanMovements")
                        .HasForeignKey("PlanDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("Parent");

                    b.Navigation("PlanDetail");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanQuestionModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.PlanModel", "Plan")
                        .WithMany("Questions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymora.Database.Entities.Utility.QuestionModel", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Gymora.Database.Entities.Utility.QuestionModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.CoachModel", "Coach")
                        .WithMany()
                        .HasForeignKey("CreateCoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymora.Database.Entities.MovementModel", null)
                        .WithMany("Questions")
                        .HasForeignKey("MovementModelId");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Gymora.Database.Entities.VideoMovementModel", b =>
                {
                    b.HasOne("Gymora.Database.Entities.CoachModel", "Coach")
                        .WithMany()
                        .HasForeignKey("CreateCoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymora.Database.Entities.MovementModel", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("Gymora.Database.Entities.MovementModel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanDetailModel", b =>
                {
                    b.Navigation("PlanMovements");
                });

            modelBuilder.Entity("Gymora.Database.Entities.PlanModel", b =>
                {
                    b.Navigation("PlanDetails");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Gymora.Database.Entities.UserModel", b =>
                {
                    b.Navigation("Coach");
                });
#pragma warning restore 612, 618
        }
    }
}
